### PR TITLE
Expose the current Jenkins job to the Groovy script as "currentJob" variable

### PR DESCRIPTION
**Pull request by greg2001**

### CODE REVIEW

**Comment by ikedam** [comment]
Thanks for the new feature.
- Would you tell me how you use this feature? I plan to add test codes and want to base on an actual usage.
- Could you squash the commits into a commit?
  - Changing line feeds cause `git blame` say all lines modified by you, and that makes it difficult to track a bug: https://github.com/jenkinsci/groovy-label-assignment-plugin/blame/master/src/main/java/jp/ikedam/jenkins/plugins/groovy_label_assignment/GroovyLabelAssignmentProperty.java
  - You can do that with `git rebase -i` and `git push --force`:  https://help.github.com/articles/about-git-rebase/
  - Please let me know if you don't do that. Don't mind, I can do that with `git cherry-pick`

**Comment by greg2001** [comment]
Hi,

> Would you tell me how you use this feature? I plan to add test codes and want to base on an actual usage. 

in your groovy script, you can reference the current Jenkins job as “currentJob” and do stuff like that:

[‘windows’, ‘linux’, ‘mac’].find {
  currentJob.name.toLowerCase().contains(it)
}

The piece of code above would automatically assign the label according to the job name.

> Could you squash the commits into a commit? 

Hopefully, I did it right. Do I need to make a new pull request? Just let me know...
[I’m a complete git noob – sorry about that.]

WBR

**Comment by ikedam** [comment]
Thanks for the use case. I'll prepare test codes.

You almost succeeded to squash commits, but something go wrong.
I expect commits like this (only one commit from you):
https://github.com/ikedam/groovy-label-assignment/commits/feature/PR-1_expected

Your current commits (there are still commits squashed):
https://github.com/ikedam/groovy-label-assignment/commits/feature/PR-1_actual

You can see what happened with `git log --topo-order`.
I suppose you merged your master to avoid an error occurred when `git push`.
You can avoid that error with `git push -f`.
So what you should do are:
- Rewind your local branch to f4e702d1fdd41d3d63fc29c30cdbd7bb13e47831 (that can be done with `git checkout -B (branchname) (commit-sha1)`).
- Push and overwrite the your branch on github (that can be done with `git push -f origin (local branchname):(remove branchname)`)
- You don't need to re-create the pull request as github automatically updates the pull requests if you overwrite the branch.

Could you try that again?
Sorry for annoying you, but I'd like you know how to use GIT as I believe it's very powerful and will help your developments.
Please let me know if that is too annoying or you aren't so interested in how to use GIT. I'll work on that instead.

**Comment by greg2001** [comment]
Hi,

> Could you try that again?

I did – looks better now. Thanks for the instructions!

**Comment by ikedam** [comment]
Perfect! Thanks.
Please wait and let me have time to write test codes.
You can do that if you're interested in writing tests.

**Comment by ikedam** [comment]
I plan to make a new release (1.1.0) next weekend.

**Comment by ikedam** [comment]
Released groovy-label-assignment-1.1.0.
It will be available in a day.

**Pull request merged**
